name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-resources:
    runs-on: ubuntu-latest
    name: Deploy Resources
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionRole
          aws-region: us-east-1

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Deploy SST Resources
        run: yarn sst deploy
